### ISSUE TITLE
Java Error on 2.4.4-RELEASE-p3 

### ISSUE THREAD

**Issue by jclemons7** [gozoinks/unifi-pfsense#146]
Hello, 

I'm getting the following error since updating to 2.4.4-RELEASE-p3, then trying to update the Ubiquiti using the normal method.  

[2.4.4-RELEASE][root@yada-yada-yad.com]/root: Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/OSInfo
at com.ubnt.service.B.R.<clinit>(Unknown Source)
at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.OSInfo
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 2 more

**Comment by jclemons7** [comment]
Fixed with this... 

https://github.com/gozoinks/unifi-pfsense/issues/142

**Comment by sultanoswing** [comment]
Thanks for the fix, jclemons7. 

Although the fix also worked for me getting the unifi controller running, my us-8-150w switch just would not adopt on the upgraded controller (my 3 APs were fine).

I have given up for now, and migrated to an instance running on my Arch Linux box instead.

The dark mysterious arts of failed unifi adoptions never ceases to amaze and annoy.
